### PR TITLE
Improve polish translation (v4)

### PR DESCRIPTION
**Pull request by kotoko**
This is continuation of https://github.com/backuppc/backuppc/pull/286. I applied same changes to the file `pl.pm` on master branch. Unfortunately I do not have running instance of backuppc v4 to test it.

### CODE REVIEW

**Comment by kotoko** [comment]
(Travis failed on linter on files I did not changed.)

**Comment by moisseev** [comment]
> 
> (Travis failed on linter on files I did not changed.)

@kotoko It is fine. We had to use perltidy from the `master` branch. Apparently perltidy developers committed some changes.

@jooola Perltidy 20200619 was released recently. If all required perltidy features were included in the release, can we switch perltidy on Travis from `master` to the latest release? And print perltidy version in Travis log?

**Comment by craigbarratt** [comment]
We previously used perltidy master to pick up some new features we needed.  But, yes, now it would be much better to switch to a stable release.

I just pushed some changes to fix the current perltidy issues.  I might have to revert them if we go to Perltidy 20200619, but I would be most happy to do that and stick with a stable perltidy.

**Comment by craigbarratt** [comment]
Thanks for the extensive polish translation issues!  I'll merge them.

**Comment by craigbarratt** [comment]
@joola, @moisseev: I set perltidy version to 20200619 and reverted my last changes.  But it fails without any log output.  So I'll need @joola to fix whatever I broke.

**Comment by craigbarratt** [comment]
I fixed it - perltidy uses numeric revisions, so I had to quote it.

**Pull request merged**
