### PR TITLE
some tweaks for current theme

### PR DESCRIPTION
**Pull request by sergeyklochko**
fresh look for standard theme.

### CODE REVIEW

**Comment by craigbarratt** [comment]
Thanks - this looks really nice.  After I try it out some more I'm tempted to make this the new default.

I'll also add it to `makeDist` and `configure.pl` so it is included in future releases.

**Comment by jirkade** [comment]
Hi, I agree it looks nicer, mostly. The only place I would change are the "DELETE" buttons next to each backup on host backup summary page. They are upper case and blue which makes them stand out of the page really drastically as if they are the most important thing there. So reverting them back to "Delete" and grayish would make them much less disrupting. After all I think deleting backups is a pretty rare action compared to everything else you can do on the page.

**Comment by sergeyklochko** [comment]
Grayed out buttons looks like disabled choice.
Red is better, but more disturbing.

I suggest to replace button with little red x-cross. I can design some
pages for you, but who will implement it? Some things can’t be done with
css.

Sorry for my english.


Sergey

Включено 30 сентября 2020 г. в 09:42:29, jirkade (notifications@github.com)
написал:

**Comment by moisseev** [comment]
>  I suggest to replace button with little red x-cross. I can design some pages for you, but who will implement it?

@sergeyklochko It is not a problem. We just need to replace the word `Delete` with a cross symbol (e.g. U+274C). I can help you with it. But this change affects other themes, so all themes should be changed appropriataly in this case.

Another option is just to use lighter color, e.g. #ccdefb instead of the #005dee.
I am not suggesting the exact color, it is merely to illustrate the idea.

**Comment by sergeyklochko** [comment]
Root of the problem, when I started to change theme was different styles
for same elements on different pages. It’s ok for ‘90 but don’t for ‘20.
I like your software. That’s why I decide to publish my substitute css.

If we want better styles and design for backuppc we beed to change html
code too, not just html.
I can design it for you and even code it to html/css, but I have no time
and good skill in perl to implement it.

/ Sergey

Включено 30 сентября 2020 г. в 10:14:16, Alexander Moisseev (
notifications@github.com) написал:

**Comment by moisseev** [comment]
If you send me desired changes in HTML code, let's say as diff of HTML source as it appears in web-browser, I would try to implement them in Perl code.

**Comment by sergeyklochko** [comment]
https://www.figma.com/file/CMYqGQmQ4w6z7at2v92YIj/Untitled?node-id=1%3A149
We can try implement this style if you all liked it. Please, do not be misguided by width of screen - this is iPad vertical view. Common it will de wider and look wide like original design.
What I need to complete design:
example strings Running Jobs and Failures. And some sensitive information on other pages.

I want to change logo a little bit to be more modern. You can see it above new design screen. Current logo is pretty good, but a little bit old fashioned. I Like font, but can't find which one used to create logo. Hope it's free or someone buy it if not.

Feel free to discuss it.

**Comment by craigbarratt** [comment]
I agree with @jirkade - the uppercase text and strong color seem too distracting, especially for the Delete button since there are so many of them.  There are several options - soften the color, make the text smaller, don't use uppercase, or move to a symbol (as already suggested).  Smaller uppercase text with a less intense shade might work well.

The intense blue color also doesn't look very good with when the "Save" button text turns red after you change a config value.

But overall this is a really good improvement, and I appreciate you working on this.  After we tweak it a bit I do plan to make this the new default in the next release.

Also, does uppercase cause problems in other languages, or does it generally do the right thing?

**Comment by sergeyklochko** [comment]
We have some problems with current colors and styles:
1) different items have same design
2) blue color is too intensive and can't be easy accented when hovered without contrast color
3) red text on blue button

I don't like those problems in my scheme, but I have no plans to publish it until yesterday and use this pages too rare, thats why I didn't solve it. They should be tweaked if you want good design.

I want to know - do you want tweak current design or want to move to something like a screenshot above?

image

**Comment by craigbarratt** [comment]
I like the screenshot you included above.  What do others think?

**Comment by moisseev** [comment]
The proposed style looks good.

I agree with @craigbarratt and @sergeyklochko , the buttons are too bright, I'd prefer softer colors too. And yes, we should use different colors for the actions buttons.

I am not sure if it worth to change the logo. The current and proposed logos looks very similar to me.

IMO web UI will be more usable if we could fit more information on the screen. So more compact tables and probably slightly decreased fonts would be convenient.

One more thing. If it is possible, please consider using fonts that readable when ClearType is turned off.

**Comment by sergeyklochko** [comment]
css live preview

image

**Comment by sergeyklochko** [comment]
[browse-tree-icon-set-svg.zip](https://github.com/backuppc/backuppc/files/5323914/browse-tree-icon-set-svg.zip)
Tree view svg icon set. It's pixel perfect png-to-svg copy of images for better feeling with 4k+ resolutions display screens.

**Comment by sergeyklochko** [comment]
new look css preview.
[BackupPC_2020_mod.css.zip](https://github.com/backuppc/backuppc/files/5332021/BackupPC_2020_mod.css.zip)

**Pull request merged**
