### PR TITLE
Rate-limit repeated log messages

### PR DESCRIPTION
**Pull request by moisseev**
using token bucket algorithm.

Issue: #303

Note that the commit doesn't fix the cause of excessive errors.

### CODE REVIEW

**Comment by guestisp** [comment]
Any chance to get this merged ? I'm flooded due to nighlty spawing multiple days and the flood is killing I/O (already bad on this machine)

**Comment by moisseev** [comment]
It's up to @craigbarratt to decide, but I don't see how merging would help you. If you want to build BackupPC from source you can do it right now from the fork: https://github.com/moisseev/backuppc-1/tree/rate-limit .
From the other hand you can just copy `bin/BackupPC` file. Just in case compare installed bin/BackupPC with one in source of the release. If you find any differences (probably just a couple of lines containing paths specific to your distribution), make appropriate changes.

**Comment by guestisp** [comment]
>  but I don't see how merging would help you

why not ? If merged, i'll be able to upgrade BackupPC from official github without using customizations coming from thirty-party forks on a production server. Nothing bad in doing that (i did multiple times before), but using the "official" version is preferable...

**Comment by craigbarratt** [comment]
@moisseev - thanks for proposing this code.  I'd prefer not to merge this since it's better to fix the root cause problem (infinite loop repeating a failed request) that was flooding the log.

**Comment by moisseev** [comment]
Totally agree, but why we can't have both? I mean I think it would be useful in general for log flooding prevention because of other potential problems (misconfigurations, bugs, etc.).

**Pull request closed without merging**
