### PR TITLE
new 2020 look mod CSS

### PR DESCRIPTION
**Pull request by sergeyklochko**
new 2020 look mod CSS

### CODE REVIEW

**Comment by craigbarratt** [comment]
I tried this, after installing the content div PR #376.  However, the formatting is really bad, so something isn't right.

Also, it would be best if the github css source is not compressed - the file is unintelligible.  Since the css files are cached by the browser, it doesn't seem worthwhile to compress it.  If you really think compression is worthwhile, it could be done by `makeDist`, but I don't think it's needed.

**Comment by sergeyklochko** [comment]
since it's compiled css, I beautify it with online tool. Everyone can do it.

Please, make tables selectable by class, current selection is really wrong:
input + p + table 
or even like this
#Content > table:nth-child(5) > tbody > tr:nth-child(9) > td:nth-child(2) > table  > tr

and, please, add #manual id to manual html parent div

**Comment by sergeyklochko** [comment]
I suggest add string to include user-defined css to header for easy overriding any parameter. 
Like this:

<html>
  <head>
    <title>BackupPC: Directory backup history for proto.mumuproject.com</title>
    <link rel=stylesheet type="text/css" href="/BackupPC/BackupPC_mod.css?version=2" title="CSSFile">
    <link rel=stylesheet type="text/css" href="/BackupPC/my.css">

someone can override font or anything else and never lost changes on updates:

body {
  font-family: lovelyfontmane
  font-size: lovelysize
  fone-weight: fontweight....

**Comment by sergeyklochko** [comment]
if you think something looking wrong, please give me screenshot AND page's html code.

**Comment by moisseev** [comment]
> If you really think compression is worthwhile, it could be done by `makeDist`, but I don't think it's needed.

I would leave it uncompressed since CSS minification in `makeDist` requires extra dependencies and complicates package building.

**Comment by sergeyklochko** [comment]
https://github.com/sergeyklochko/backuppc-2020-theme-CSS
this is vanila-based (No any named div's, tables or #Contents pages) HTML CSS for everyone who want CSS sources (SASS)

**Comment by craigbarratt** [comment]
Thanks for the updates.  Sorry, I'm not very familiar with CSS.  I don't understand the differences and benefits of vanilla vs live.

The latest css file in this PR works for me now.  I'm not sure why the earlier one didn't work.

A couple of comments / questions:
* when you browse a backup, the path entries (which are links) that follow "Contents of " are in upper case.  Since it's a path it needs to maintain its original case
* in the config editor, can the "add" and "delete" buttons be next to each other horizontally like they are currently?  For long config entries the vertical button pair uses too much space
* in the left nav bar, the host selection box slight truncates the bottom of descending characters
* can the fixed font size for log files be a bit smaller?  Log files tend to be very long, and the font seems too large

I'm not sure what extra tags you want or need. Perhaps @moisseev could help add them?

Having an additional CSS include for local settings could be a good idea.  It should be able to be included in `$Conf{CgiHeaders}` for users that want that feature.

The Github package you link to has svg files and new icons, which you also included in the comments in the prior PR.  Are you proposing to switch to them?

**Comment by sergeyklochko** [comment]
vanilla - works with original 4.4.0 without any additional PR
live - latest compiled version. currently is the same versions, but some futures require to change HTML code a little bit.
All changes I request allow old css work well.

1 fixed in live css
2 is it XFER tab? can't select it until tables get their names.
3 fixed in live css
4 will be fixed when <pre> tag get 'log' class

**Comment by craigbarratt** [comment]
Just checking on the status.  I tried `BackupPC_2020_mod.css` from `sergeyklochko/backuppc` and two of the issues I mentioned are fixed - thanks!

The other two (smaller font for `pre` and horizontal alignment for Add and Delete buttons for config arrays and hashes) remain.

I noticed that the tags that @moisseev added don't appear to be used.  Do you plan to use those tags, and are there other tags you need?

**Comment by sergeyklochko** [comment]
image

I have no live server with changes. I think I fix it for examples html pages.

Same for logs and paths.

Probably you need to clear your browser cache. If it keep unchanged? please send YOUR html pages to me.

**Comment by craigbarratt** [comment]
I turned caching off (on Chrome) and also tried Safari.  It still shows a vertical arrangement. I also double-checked the loaded css in the chrome debugger file against your version - they match.

What's the best way to send you the html?

**Comment by sergeyklochko** [comment]
send via email or link to downloadable file to sergey@klochko.ru

**Comment by sergeyklochko** [comment]
image

**Comment by craigbarratt** [comment]
Thanks for the update.  Yes, that fixes it for ClientNameAlias.  However, it stacks vertically in every other case (eg, ` RsyncSshArgs` and `RsyncArgs` in the Xfer tab).

**Comment by sergeyklochko** [comment]
I have no file for this page

**Comment by sergeyklochko** [comment]
i think i fix buttons.

**Comment by craigbarratt** [comment]
Thanks for the latest fix - the Add / Delete buttons are now horizontal.  However, the horizontal space they occupy leaves a significant gap between the buttons and the field they refer to.  Is it possible tighten that up?  Example in attached screenshot - extraneous whitespace in blue circles.

Screen Shot 2020-10-24 at 9 47 00 AM

**Comment by sergeyklochko** [comment]
unfortunately, I know only two layouts of tables: 
auto width - content aware, but produce large spaces when table width set to 100%
fixed width - kill spaces, but some language-specific words sometime not fit to buttons/cells. Since you have many languages, I choose first way in last version instead second before.

If you want to squeeze space you can add strings to end of css:

// ugly buttons fix
.editSubTable td:first-child {
  width: desired-width;
}

where desired width in percents, pixels or ems.

Since I never meet tables before, probably exists other way to squieeze this space. 

Or

you can add 

//ugly table fix
table {
  width: auto
}

But you should specify width of every cell type relative to other to beautify your table.

image

tables it to ancient tool for markup pages.

**Comment by craigbarratt** [comment]
Is this considered complete and ready to merge?  I'm not sure whether you are waiting for more tags to be added or not.

**Comment by sergeyklochko** [comment]
it's my live version for backuppc. I have no time to make it perfect. may be next year. it's usable with spacesyou don't like or you can add to end of file next strings:
table {
width: auto
}

it's broke config table header a little bit, but still acceptable.

**Comment by LordSimal** [comment]
I am curious what the status here is. Will it be merged and release in the next update (whenever that happens)?

**Comment by michieltimmers** [comment]
Would love to see this merged! Hope you find time to make it perfect

**Pull request merged**
