### PR TITLE
Modern theme

### PR DESCRIPTION
**Pull request by EquisTango**
This is a new CSS style sheet proposal, using modern visual styles and bigger fonts at consistent sizes.

It works on BackupPC 3.3 and 4.0 (you only need to change $Conf{CgiCSSFile} = 'BackupPC_modern.css'; in config.pl to use it).

### CODE REVIEW

**Comment by joebordes** [comment]
looks nice. good work

**Comment by craigbarratt** [comment]
Thanks!!  It looks really nice.  I made this the standard css file for 4.x.  (Moved to the conf/ directory which is where the CSS source lives.)

The only minor quibble is there is quite a lot of whitespace between the EditConfig parameter names and the corresponding boxes when the browser window is large.  But I like how it rescales in a sensible way when you resize the browser window.

**Comment by EquisTango** [comment]
That's great. I'll check the spacing in EditConfig.

**Comment by moisseev** [comment]
IMO the modern theme is an ergonomic regression.

- @EquisTango Would you consider changing fonts to something more readable?
2017-03-11 11_19_58-program manager
2017-03-11 11_21_05-backuppc server status - pale moon

- Previous theme adjusts table column width to content size. Modern one adjusts table width to window size. It makes tables harder to read on wide screens.

- IMO font size of previous theme was optimal. It was big enough for reading. Bigger fonts mean less information on the screen.

**Comment by EquisTango** [comment]
Hi @moisseev, in your screenshots there's no font anti-aliasing. That's why the new font look less readable. The new font is in fact more readable given that you are using some form of font smoothing or anti-aliasing (and probably hinting), which is virtually ubiquitous on modern operating systems.

As for the table width problem, I'll be making some adjustments to avoid excessive spacing. However consider that some white space also adds up to readability (as long as it's not excessive).

Finally, yes, there's much information on screen at the same time and yes, smaller font makes more of it visible without scroll. I think a lot of work should be done to enhance that, like using a more efficient layout (bullet lists are not the best for this), creating a dashboard, segmenting information and sometimes even remove or hide nonessential information.

I'm willing to work on this, if such changes would be accepted. This is not just CSS, I need to edit Perl files to emit correct and modern HTML.

**Comment by moisseev** [comment]
@EquisTango, I hope it is just a start and you will continue working on the web interface. But "modern HTML" scares me a bit :)

Yes, I'm never using anti-aliasing. I can't read blurring fonts. Anti-aliasing is acceptable for me just on very high resolution displays like "retina". And I know in person a lot of people who hates any form of font smoothing.

Since we are discussing the default theme that we have out of the box, it would be great if it would be universal as possible, suitable for most cases. I understand that universality comes with a cost.

**Comment by moisseev** [comment]
@EquisTango I think we should highlight hyperlinks somehow.
Users shouldn't have to guess to find out where they can click.

2017-03-22 12_25_09-backuppc_ browse backup 1332 for www_fsroot - pale moon

2017-03-22 12_34_47-settings

**Comment by craigbarratt** [comment]
I agree with Alexander.  Some links (especially like "history") are
invisible to any user who is not very familiar with the interface.

Craig

**Comment by EquisTango** [comment]
Links are now blueish, I added a maximum table width for big screens, and some minor fixes. #73

**Pull request merged**
