### PR TITLE
Update shebangs to '#!/usr/bin/env perl'

### PR DESCRIPTION
**Pull request by jooola**
Replace all old shebangs to '#!/usr/bin/env perl'.

I'm unsure if this has a big impact.

### CODE REVIEW

**Comment by hobbes1069** [comment]
Is there a need for BackupPC to use perl from a non-standard location? For packaging purposes absolute paths are enforced on Fedora.

**Comment by jooola** [comment]
@hobbes1069 I assumed it is a good practice. But I do not intend to break anything, so maybe this PR is not needed. Still worth the discussion.

**Comment by moisseev** [comment]
The "standard" location of the perl executable depends on distribution. For instance it could be `/usr/bin/perl` or `/usr/local/bin/perl`. This PR makes source code distribution agnostic. That a very important IMO. In rare cases when the distribution policy requires absolute paths, it is a package maintainer's duty to patch shebangs.

**Comment by craigbarratt** [comment]
Currently configure.pl replaces the shebangs with the local system's perl path, if the source file shebang ends in "bin/perl".  So the installation process currently makes them all consistent.

This change will cause configure.pl to not change the shebang on installation, and the detected perl path or command-line argument will not be used.  That could break some packaging scripts.

Also, this change breaks travis-CI.  Looking at the logs, it seems BackupPC::XS is not found, so perhaps there is some issue with #!/usr/bin/env perl not getting the same perl version.

Craig

**Pull request closed without merging**
