### PR TITLE
[docs] Add nginx sample config

### PR DESCRIPTION
**Pull request by guestisp**
Add nginx sample configuration file with S/CGI

### CODE REVIEW

**Comment by SpareSimian** [comment]
I'm using fastcgi_pass. How does scgi_pass compare? What's the difference?

**Comment by guestisp** [comment]
> I'm using fastcgi_pass. How does scgi_pass compare? What's the difference?

Honestly ? I don't know. :-)
I've used scgi because docs are saying that scgi is suggested (in apache)

Didn't know that fastcgi would work with an scgi server.

**Comment by guestisp** [comment]
@SpareSimian  could you please share your nginx configuration ? i've tried connecting nginx via fastcgi to bpc scgi and it doesn't work.

**Comment by SpareSimian** [comment]
[etc-nginx-conf.d-backuppc.conf.txt](https://github.com/backuppc/backuppc/files/4065785/etc-nginx-conf.d-backuppc.conf.txt)

Place this in /etc/nginx/conf.d/backuppc.conf. I've changed my LAN domain to example.lan in the file. 

I'm using the nginx package for CentOS7 from the nginx website, installed by yum from their repo.

**Comment by SpareSimian** [comment]
I installed fcgiwrap from the epel repo. I enabled it with:

systemctl enable fcgiwrap@nginx.socket

I added user nginx to the apache and backuppc groups.

**Comment by guestisp** [comment]
@SpareSimian are you using BackupPC v4 ? Because I don't have `BackupPC_Admin` but only `BackupPC_Admin_SCGI` and pointing FastCGI to the SCGI port (opened by BackupPC) is not working

Anyway, as using FastCGI or SCGI in nginx is almost the same (just a couple of line changes in configuration) I still think that this PR would be useful

**Comment by SpareSimian** [comment]
Yes, I'm using v4 from the hobbes1069-BackupPC copr repo.  That package has the following Admin files:

/usr/libexec/BackupPC/BackupPC_Admin
/usr/share/BackupPC/bin/BackupPC_Admin_SCGI
/usr/share/BackupPC/lib/BackupPC/CGI/AdminOptions.pm
/usr/share/BackupPC/sbin/BackupPC_Admin

**Comment by guestisp** [comment]
Probably, if installed using SCGI, the `BackupPC_Admin` doens't get installed because I don't have it

**Comment by guestisp** [comment]
Anyway, to use BackupPC in FastCGI mode with nginx, `fcgiwrapper` is needed, the SCGI is native, doesn't require any extra software except 3 configuration line and it's also the suggested working mode for BackupPC so I don't see why using a thirtyparty modules to get the same result as the stock one

**Comment by SpareSimian** [comment]
I realized what you meant by SCGI being "native". You mean that BackupPC provides an SCGI server "in the box". Which is probably good enough because it's never going to be under high web load. FastCGI has more parallelism and is designed for lots of simultaneous users, not a normal use case for BackupPC. OTOH, if you already need fcgiwrapper for some other application, you can use the same service to handle the small extra load for BackupPC. I'm using it because most of the examples on the web are for FastCGI. So your solution is great for a dedicated backup server, while mine is better for a server running many different services.

**Comment by guestisp** [comment]
Well, even if you are using the same server to host websites with fastcgi, my solution is still good. Just use the native scgi module (in nginx) to connect to the native scgi server in backuppc ......

You aren't forced to remove fastcgi from the server. backuppc would use scgi and everything else fastcgi

Using FastCGI doesn't seem to be a suggested configuration, as official docs only talks about SCGI, not FastCGI, so I don't see any advantage to use FastCGI with nginx but only drawbacks. 
SCGI is native, doesn't require any additional module, is the suggested configuration and doesn't conflict with any existing fastcgi configuration. It's almost "plug&play"

**Pull request merged**
