### PR TITLE
feat(ClientWifiAlias): added an extra parameters to allow wifi backup

### PR DESCRIPTION
**Pull request by martintamare**
We use backuppc a lot but we are missing one feature.
We have a lots of laptop which connect randomly on wired connections or on wireless connections.

We try advanced DNS stuff but were unable to have a decent result.
Thus we made this patch.

Similar to ClientNameAlias, we implemented ClientWifiAlias.

What does it do ?

Instead a fetching a unique hostIP, we build an array of valid IP and loop on them.

I know it's far from being ready to merge but I'd like feedback on how to improve it :
- ClientWifiAlias : maybe make this an array ? or a better name ?

Cheers,

### CODE REVIEW

**Comment by moisseev** [comment]
What if we just add ability to specify `$Conf{ClientNameAlias}` as an array (it should accept both: a string or an array of strings) instead of adding the new `$Conf{ClientWifiAlias}` parameter? It will allow to add any number of alternative host names or IPs.

```perl
$Conf{ClientNameAlias} = 'hostname';
$Conf{ClientNameAlias} = ['hostname1', 'hostname2', 192.168.1.1];
```

**Comment by martintamare** [comment]
I like that !
Doing soon ...

**Comment by martintamare** [comment]
Seems ok to me, I backported this to v3, it worked like a charmed :)
By the way, any news on a Debian package of the v4 ?

**Comment by craigbarratt** [comment]
I definitely prefer the approach of allowing $Conf{ClientNameAlias} to be an array, rather than adding a new config variable.  I'll update the config editor to handle the array case.

**Comment by craigbarratt** [comment]
I pushed some edits; in particular, hosts in ClientNameAlias are processed in order, so the firs good one matches (previously, using a hash, the order is not determinant.  Can you retest before I release this?  Thanks.

**Comment by martintamare** [comment]
Checking soon

**Pull request merged**
