### PR TITLE
Update webui logo

### PR DESCRIPTION
**Pull request by moisseev**
Issue: #323

### CODE REVIEW

**Comment by craigbarratt** [comment]
@moisseev - I tried top-of-tree and the BackupPC logo doesn't scale to fit the space available.  Here's a screenshot.
Screen Shot 2020-04-05 at 2 54 37 PM

**Comment by moisseev** [comment]
@craigbarratt , I think it is browser specific issue. I cannot reproduce it with latest Firefox and Palemoon. What browser are you using?

**Comment by craigbarratt** [comment]
Chrome 80.0.3987.149 on Mac OSX 10.14.6

**Comment by SpareSimian** [comment]
The search expression you want is "free cross browser testing". The few hits I checked offer a short free trial, though.

**Comment by moisseev** [comment]
@craigbarratt , I don't have OSX at hand. I've checked on Chrome 80.0.3987.163 on Windows7 and the logo scales as expected.

**Comment by craigbarratt** [comment]
Sorry about the false alarm.  The browser had an old cached BackupPC_stnd.css.  After I forced that to reload, then it worked fine.

**Pull request merged**
